// webai-bridge-cxx: header for the C ABI used by cxx.
//
// The C ABI itself is generated by the cxx bridge block in
// `src/lib.rs`; this header is included into the C++ side of the bridge
// via `include!("wrapper.h")` so the cxx-generated shim can resolve the
// `WebkitView` type and the `::rust` namespace.
//
// The cxx bridge block declares `type WebkitView;`. cxx emits
// `using WebkitView = ::WebkitView;` in the generated shim and expects
// this file to define the typedef so the two name spaces (WPE and cxx)
// line up at link time.

#ifndef WEBAI_BRIDGE_CXX_WRAPPER_H
#define WEBAI_BRIDGE_CXX_WRAPPER_H

#include <cstdint>

// Pull in the cxx-generated `rust::Str` / `rust::String` adapter types.
// The include path is supplied by `cxx-build` via `OUT_DIR/cxxbridge/include`.
#include <rust/cxx.h>

extern "C++" {

// Forward-declare the WPE / GLib / cog types. The bodies come from the
// cogcore, libwpe-1.0, and wpe-webkit-2.0 headers at link time.
struct _WebKitWebView;
struct _WebKitWebContext;
struct _WebKitUserContentManager;
struct _WebKitUserScript;
struct _CogShell;
struct _CogPlatform;

typedef struct _WebKitWebView WebKitWebView;
typedef struct _WebKitWebContext WebKitWebContext;
typedef struct _WebKitUserContentManager WebKitUserContentManager;
typedef struct _WebKitUserScript WebKitUserScript;
typedef struct _CogShell CogShell;
typedef struct _CogPlatform CogPlatform;

// Aliases that give the cxx shim and the wrapper a single vocabulary.
typedef WebKitWebView WebkitWebView;
typedef WebKitWebContext WebkitWebContext;
typedef WebKitUserContentManager WebkitUserContentManager;

// `WebkitView` is the type cxx expects in every bridge function. Alias
// it to the WPE WebView here so the shim and the wrapper resolve to
// the same pointer type.
typedef WebkitWebView WebkitView;

} // extern "C++"

#endif // WEBAI_BRIDGE_CXX_WRAPPER_H
